language: objective-c
osx_image: xcode9.2

script:
  - set -o pipefail
  - xcodebuild -project 'Log4s.xcodeproj' -target 'Tests' -configuration Debug -sdk iphonesimulator clean build ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO | xcpretty -c

